import type { Config } from 'tailwindcss';
import defaultTheme from 'tailwindcss/defaultTheme';
import {
  colorScale,
  getColor,
  getColors,
  radixColors,
  radixGrayColors,
} from './app/lib/tailwind-utils';

export default {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx,ts,tsx}', './pages/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    colors: {
      ...getColors(radixGrayColors, true),
      ...getColors(radixColors),
      whiteA: getColor('white', colorScale, true),
      blackA: getColor('black', colorScale, true),
      surface: 'var(--color-surface)',
      panel: 'var(--color-panel)',
      overlay: 'var(--color-overlay)',
      'panel-solid': 'var(--color-panel-solid)',
      'panel-translucent': 'var(--color-panel-translucent)',
      transparent: 'transparent',
      card: 'var(--card)',
      'card-foreground': 'var(--card-foreground)',
      gray: {
        1: 'var(--gray-1)',
        2: 'var(--gray-2)',
        3: 'var(--gray-3)',
        4: 'var(--gray-4)',
        5: 'var(--gray-5)',
        6: 'var(--gray-6)',
        7: 'var(--gray-7)',
        8: 'var(--gray-8)',
        9: 'var(--gray-9)',
        10: 'var(--gray-10)',
        11: 'var(--gray-11)',
        12: 'var(--gray-12)',
        a1: 'var(--gray-a1)',
        a2: 'var(--gray-a2)',
        a3: 'var(--gray-a3)',
        a4: 'var(--gray-a4)',
        a5: 'var(--gray-a5)',
        a6: 'var(--gray-a6)',
        a7: 'var(--gray-a7)',
        a8: 'var(--gray-a8)',
        a9: 'var(--gray-a9)',
        a10: 'var(--gray-a10)',
        a11: 'var(--gray-a11)',
        a12: 'var(--gray-a12)',
      },
      accent: {
        1: 'var(--accent-1)',
        2: 'var(--accent-2)',
        3: 'var(--accent-3)',
        4: 'var(--accent-4)',
        5: 'var(--accent-5)',
        6: 'var(--accent-6)',
        7: 'var(--accent-7)',
        8: 'var(--accent-8)',
        9: 'var(--accent-9)',
        10: 'var(--accent-10)',
        11: 'var(--accent-11)',
        12: 'var(--accent-12)',
        a1: 'var(--accent-a1)',
        a2: 'var(--accent-a2)',
        a3: 'var(--accent-a3)',
        a4: 'var(--accent-a4)',
        a5: 'var(--accent-a5)',
        a6: 'var(--accent-a6)',
        a7: 'var(--accent-a7)',
        a8: 'var(--accent-a8)',
        a9: 'var(--accent-a9)',
        a10: 'var(--accent-a10)',
        a11: 'var(--accent-a11)',
        a12: 'var(--accent-a12)',
      },
      background: 'var(--background)',
      foreground: 'var(--foreground)',
      muted: {
        DEFAULT: 'var(--muted)',
        foreground: 'var(--muted-foreground)',
      },
      border: {
        DEFAULT: 'var(--border)',
        active: 'var(--border-active)',
      },
      ring: 'var(--ring)',
      primary: {
        DEFAULT: 'var(--primary)',
        foreground: 'var(--primary-foreground)',
      },
      secondary: {
        DEFAULT: 'var(--secondary)',
        foreground: 'var(--secondary-foreground)',
      },
      destructive: {
        DEFAULT: 'var(--destructive)',
        foreground: 'var(--destructive-foreground)',
      },
      info: {
        DEFAULT: 'var(--info)',
        foreground: 'var(--info-foreground)',
      },
      success: {
        DEFAULT: 'var(--success)',
        foreground: 'var(--success-foreground)',
      },
      warning: {
        DEFAULT: 'var(--warning)',
        foreground: 'var(--warning-foreground)',
      },
      error: {
        DEFAULT: 'var(--error)',
        foreground: 'var(--error-foreground)',
      },
      focus: {
        DEFAULT: 'var(--focus)',
        visible: 'var(--focus-visible)',
      },
      hover: {
        DEFAULT: 'var(--hover)',
        accent: 'var(--hover-accent)',
      },
    },
    border: {},
    borderRadius: {
      1: 'var(--radius-1)',
      2: 'var(--radius-2)',
      3: 'var(--radius-3)',
      4: 'var(--radius-4)',
      5: 'var(--radius-5)',
      6: 'var(--radius-6)',
      item: 'max(var(--radius-2),var(--radius-full))',
      full: '9999px',
    },
    boxShadow: {
      1: 'var(--shadow-1)',
      2: 'var(--shadow-2)',
      3: 'var(--shadow-3)',
      4: 'var(--shadow-4)',
      5: 'var(--shadow-5)',
      6: 'var(--shadow-6)',
    },
    fontSize: {
      1: 'var(--font-size-1)',
      2: 'var(--font-size-2)',
      3: 'var(--font-size-3)',
      4: 'var(--font-size-4)',
      5: 'var(--font-size-5)',
      6: 'var(--font-size-6)',
      7: 'var(--font-size-7)',
      8: 'var(--font-size-8)',
      9: 'var(--font-size-9)',
    },
    lineHeight: {
      1: 'var(--line-height-1)',
      2: 'var(--line-height-2)',
      3: 'var(--line-height-3)',
      4: 'var(--line-height-4)',
      5: 'var(--line-height-5)',
      6: 'var(--line-height-6)',
      7: 'var(--line-height-7)',
      8: 'var(--line-height-8)',
      9: 'var(--line-height-9)',
    },
    letterSpacing: {
      1: 'var(--letter-spacing-1)',
      2: 'var(--letter-spacing-2)',
      3: 'var(--letter-spacing-3)',
      4: 'var(--letter-spacing-4)',
      5: 'var(--letter-spacing-5)',
      6: 'var(--letter-spacing-6)',
      7: 'var(--letter-spacing-7)',
      8: 'var(--letter-spacing-8)',
      9: 'var(--letter-spacing-9)',
    },
    fontFamily: {
      sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      mono: ['Fira Code', ...defaultTheme.fontFamily.mono],
      display: ['Poppins', ...defaultTheme.fontFamily.sans],
      body: ['Roboto', ...defaultTheme.fontFamily.sans],
    },
    extend: {
      spacing: {
        'rx-1': 'var(--space-1)',
        'rx-2': 'var(--space-2)',
        'rx-3': 'var(--space-3)',
        'rx-4': 'var(--space-4)',
        'rx-5': 'var(--space-5)',
        'rx-6': 'var(--space-6)',
        'rx-7': 'var(--space-7)',
        'rx-8': 'var(--space-8)',
        'rx-9': 'var(--space-9)',
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
} satisfies Config;
